server.port=9085
spring.application.name=vfprint

spring.jpa.hibernate.ddl-auto=update

# spring.datasource.url=jdbc:postgresql://14.225.255.33:5432/vfpricecal
# spring.datasource.username=vfprint
# spring.datasource.password=vfprint191002@th

spring.datasource.url=jdbc:postgresql://localhost:5432/vfprintcal
spring.datasource.username=postgres
spring.datasource.password=258456


spring.jpa.show-sql=true


spring.docker.compose.enabled=false

# Ép Spring bỏ qua việc tự động cấu hình Security mặc định
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

jwt.secret=IG3G07Hy1d3AbEu/KcnPOEfvh1BcMQfqHFsePTx0K0E=
jwt.expiration=86400000





spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vfpricecal.service@gmail.com
# Điền Mật khẩu ứng dụng (App Password) vào đây, KHÔNG PHẢI mật khẩu chính của bạn
spring.mail.password=lvjq hysm gjpx dbwh
# Các cấu hình bảo mật đi kèm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true